// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCkjzWqkYlpp76Pxy5b9LYxZ7Wqw6sKlg',
    appId: '1:516336530872:web:3d3004fcf687ffc04e0b4d',
    messagingSenderId: '516336530872',
    projectId: 'takki-chat',
    authDomain: 'takki-chat.firebaseapp.com',
    storageBucket: 'takki-chat.firebasestorage.app',
    measurementId: 'G-EWGGR20NQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJZ7hrkiZlReIpZKYba47E_q4gSshYjbY',
    appId: '1:516336530872:android:cf6d1a3bd7ef30f74e0b4d',
    messagingSenderId: '516336530872',
    projectId: 'takki-chat',
    storageBucket: 'takki-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbTsSpOLwVWpfmagfUTQSac4kz7xonqwc',
    appId: '1:516336530872:ios:13375cb35a2b0a7e4e0b4d',
    messagingSenderId: '516336530872',
    projectId: 'takki-chat',
    storageBucket: 'takki-chat.firebasestorage.app',
    iosBundleId: 'com.chat.takki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbTsSpOLwVWpfmagfUTQSac4kz7xonqwc',
    appId: '1:516336530872:ios:13375cb35a2b0a7e4e0b4d',
    messagingSenderId: '516336530872',
    projectId: 'takki-chat',
    storageBucket: 'takki-chat.firebasestorage.app',
    iosBundleId: 'com.chat.takki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCkjzWqkYlpp76Pxy5b9LYxZ7Wqw6sKlg',
    appId: '1:516336530872:web:67abc08a0b30457f4e0b4d',
    messagingSenderId: '516336530872',
    projectId: 'takki-chat',
    authDomain: 'takki-chat.firebaseapp.com',
    storageBucket: 'takki-chat.firebasestorage.app',
    measurementId: 'G-DZP2C6RZ5N',
  );
}
